### ISSUE TITLE
PyPi pip install xdrt does not correctly compile.

### ISSUE THREAD

**Issue by jonasteuwen** [NKI-AI/xdrt#1]
When trying to install xdrt from PyPi, you might run into a compilation error. This needs further investigation. Installing from source as described should currently work.

**Comment by ivanzhovannik** [comment]
Hi @jonasteuwen,

I have encountered CMake issues for both PyPi and source installation - [xdrt_installation_traceback_CMake-fails-to-build-wheel.txt](https://github.com/NKI-AI/xdrt/files/8390470/installation_traceback_CMake-fails-to-build-wheel.txt). Maybe it is due to CMake not able to define compiler properly? I am not sure how to force a standard compiler on it.

This [link](https://perso.uclouvain.be/allan.barrea/opencv/building_tools.html) was useful to configure *CMake* and *MinGW* for Windows - maybe good to add it somewhere.
